// <auto-generated />
using System;
using FinalMarzo.net.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FinalMarzo.net.Migrations
{
    [DbContext(typeof(MyDbContext))]
    [Migration("20250302145344_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.2")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Espaciosestacionamiento", b =>
                {
                    b.Property<int>("IdEspacio")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdEspacio"));

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("NumeroEspacio")
                        .HasColumnType("int");

                    b.Property<string>("Sector")
                        .HasColumnType("longtext");

                    b.Property<string>("TipoEspacio")
                        .HasColumnType("longtext");

                    b.HasKey("IdEspacio");

                    b.HasIndex("NumeroEspacio")
                        .IsUnique();

                    b.ToTable("EspaciosEstacionamiento");
                });

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Reserva", b =>
                {
                    b.Property<int>("IdReserva")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdReserva"));

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("FechaExpiracion")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("FechaReserva")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdEspacio")
                        .HasColumnType("int");

                    b.HasKey("IdReserva");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdEspacio");

                    b.ToTable("Reservas");
                });

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Usuario", b =>
                {
                    b.Property<int>("IdUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdUsuario"));

                    b.Property<string>("Contrasena")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("IdUsuario");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");
                });

            modelBuilder.Entity("FinalMarzo.net.Models.Cliente", b =>
                {
                    b.Property<int>("IdCliente")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdCliente"));

                    b.Property<string>("Email")
                        .HasColumnType("varchar(255)");

                    b.Property<DateTime?>("FechaRegistro")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("ResetToken")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("ResetTokenExpiry")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Telefono")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.Property<string>("VehiculoPlaca")
                        .IsRequired()
                        .HasColumnType("varchar(255)");

                    b.HasKey("IdCliente");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.HasIndex("Telefono")
                        .IsUnique();

                    b.HasIndex("VehiculoPlaca")
                        .IsUnique();

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("FinalMarzo.net.Models.Pago", b =>
                {
                    b.Property<int>("IdPago")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("IdPago"));

                    b.Property<string>("Estado")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("FechaPago")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("IdCliente")
                        .HasColumnType("int");

                    b.Property<int>("IdReserva")
                        .HasColumnType("int");

                    b.Property<string>("MetodoPago")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<decimal>("Monto")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("IdPago");

                    b.HasIndex("IdCliente");

                    b.HasIndex("IdReserva");

                    b.ToTable("Pagos");
                });

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Reserva", b =>
                {
                    b.HasOne("FinalMarzo.net.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalMarzo.net.Data.Models.Espaciosestacionamiento", "IdEspacioNavigation")
                        .WithMany("Reservas")
                        .HasForeignKey("IdEspacio")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdEspacioNavigation");
                });

            modelBuilder.Entity("FinalMarzo.net.Models.Pago", b =>
                {
                    b.HasOne("FinalMarzo.net.Models.Cliente", "IdClienteNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdCliente")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FinalMarzo.net.Data.Models.Reserva", "IdReservaNavigation")
                        .WithMany("Pagos")
                        .HasForeignKey("IdReserva")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("IdClienteNavigation");

                    b.Navigation("IdReservaNavigation");
                });

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Espaciosestacionamiento", b =>
                {
                    b.Navigation("Reservas");
                });

            modelBuilder.Entity("FinalMarzo.net.Data.Models.Reserva", b =>
                {
                    b.Navigation("Pagos");
                });

            modelBuilder.Entity("FinalMarzo.net.Models.Cliente", b =>
                {
                    b.Navigation("Pagos");

                    b.Navigation("Reservas");
                });
#pragma warning restore 612, 618
        }
    }
}
